// app/filial/layout.jsx
import RotaProtegida from "@/components/RotaProtegida/RotaProtegida";
import "../globals.css";
import NextTopLoader from "nextjs-toploader";
import { Sidebar } from "@/components/LayoutMatriz/sidebar/index";
import { Header } from "@/components/LayoutMatriz/header/index";
import { SidebarProvider } from "@/components/LayoutMatriz/sidebar/sidebar-context";
import FooterMatriz from "@/components/FooterMatriz/FooterMatriz";

import { cookies } from "next/headers";

export const metadata = {
  title: "Music House",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies();

  const requestUser = await fetch("http://localhost:8080/auth/auth-check", {
    method: "GET",
    headers: {
      cookie: cookieStore.toString(),
    },
    credentials: "include",
    cache: "no-store",
  });

  const USER = await requestUser.json();

  return (
    <RotaProtegida permitido={1}>
      <SidebarProvider>
        <NextTopLoader color="#5750F1" showSpinner={false} />

        <div className="flex min-h-screen">
          <Sidebar />

          <div className="w-full bg-gray-2 bg-gray-100">
            <Header user={USER} />

            <main className="isolate px-10 py-5 mx-auto w-full overflow-hidden">
              {children}
            </main>
            <FooterMatriz />
          </div>
        </div>
      </SidebarProvider>
    </RotaProtegida>
  );
}
