import RotaProtegida from '@/components/RotaProtegida/RotaProtegida';
import '../globals.css';

export const metadata = {
  title: 'Music House',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return <RotaProtegida permitido={4}>{children}</RotaProtegida>;
}
