import RotaProtegida from "@/components/RotaProtegida/RotaProtegida";
import "../globals.css";
import NextTopLoader from "nextjs-toploader";
import { Sidebar } from "@/components/LayoutFilial/sidebar";
import { Header } from "@/components/LayoutFilial/header";
import { SidebarProvider } from "@/components/LayoutFilial/sidebar/sidebar-context";
import FooterFilial from "@/components/FooterFilial/FooterFilial";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Music House",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies();


  const token = cookieStore.get("token");
  if (!token) {
    redirect("/");
  }

  const requestUser = await fetch("http://localhost:8080/auth/auth-check/franquia", {
    method: "GET",
    headers: {
      cookie: cookieStore.toString(),
    },
    credentials: "include",
    cache: "no-store",
  });

  
  if (!requestUser.ok) {
    redirect("/");
  }

  const USER = await requestUser.json();

  return (
    <RotaProtegida permitido={2}>
      <SidebarProvider>
        <NextTopLoader color="#5750F1" showSpinner={false} />

        <div className="flex min-h-screen">
          <Sidebar />

          <div className="w-full bg-gray-100">
            <Header
              user={USER}
              cidade={USER.franquia?.cidade}
              franquia_endereco={USER.franquia?.endereco_completo}
            />

            <main className="isolate px-10 py-5 mx-auto w-full max-w-screen-2xl overflow-hidden">
              {children}
            </main>

            <FooterFilial />
          </div>
        </div>
      </SidebarProvider>
    </RotaProtegida>
  );
}